<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="deldsood175052" name="Test1" tests="1" failures="1" timestamp="5 Mar 2017 05:48:05 GMT" time="37.69" errors="0">
  <testcase name="verifyUser" time="7.934" classname="test.LoginPageTest">
    <failure type="java.lang.AssertionError" message="Expected: fail">
      <![CDATA[java.lang.AssertionError: Expected: fail
	at test.LoginPageTest.verifyUser(LoginPageTest.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- verifyUser -->
</testsuite> <!-- Test1 -->
